add_executable(openpressod_config_test openpressod_config_test.cpp)
target_link_libraries(openpressod_config_test PRIVATE config_objs GTest::gtest_main)
gtest_add_tests(TARGET openpressod_config_test)

add_executable(libopenpresso_config_maker_test libopenpresso_config_maker_test.cpp)
target_link_libraries(libopenpresso_config_maker_test PRIVATE config_objs GTest::gtest_main)
gtest_add_tests(TARGET libopenpresso_config_maker_test)