#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop  "@OPENPRESSOD_SERVICE_NAME@" >/dev/null 2>&1 || true
            systemctl disable "@OPENPRESSOD_SERVICE_NAME@" >/dev/null 2>&1 || true
        fi
    ;;
esac

exit 0